### ISSUE TITLE
Path wrong when Bard is top level

### ISSUE THREAD

**Issue by edalzell** [jacksleight/statamic-distill#11]
## Bug Description

If you have data like:

```yaml
body_content:
  -
    type: set
    attrs:
      id: lwtjbq5y
      values:
        type: headings_content
        blocks:
          -
            id: lwtjbr8f
            pre_heading: 'Reposted from Anadolu Ajansı'
            heading: 'Chicago Turkish Festival draws more than 10,000 people'
            heading_type: h1
            type: heading_lead
            enabled: true
            container_classes: col-12
```

Where `body_content` is a bard field & `headings_content` is a replicator and you do `$items = Distill::query($e)->type('set:heading_lead')->get();`, the `path` you get is `body_content.0.blocks.0` instead of `body_content.0.attrs.values.blocks.0`.
