### ISSUE TITLE
`whereNotNull` returns error

### ISSUE THREAD

**Issue by edalzell** [jacksleight/statamic-distill#12]
If you have content like:

```yaml
body_content:
  -
    type: set
    attrs:
      id: lwtjbq5y
      values:
        type: headings_content
        blocks:
          -
            id: lwtjbr8f
            pre_heading: 'Reposted from Anadolu Ajansı'
            heading: 'Chicago Turkish Festival draws more than 10,000 people'
            heading_type: h1
            type: heading_lead
            enabled: true
            container_classes: col-12
```

And you try to query:

```php
$items = Distill::query($e)
            ->type('set:heading_lead')
            ->whereNotNull('container_classes')
            ->get();
```

You get an error: 
![CleanShot 2024-12-09 at 12 17 00@2x](https://github.com/user-attachments/assets/8d40779f-52b2-4a8b-b90d-2a6ab529384f)
